### ISSUE TITLE
README dosyasındaki projenin yaptığı alan belirlenip LAN için C üzerinde nasıl programlayabiliriz üzerine araştırma yapılacak.

### ISSUE THREAD

**Issue by Onur-TURAN** [skylab-kulubu/SKY-SEC_Scanner#5]

**Comment by Sushkyn** [comment]
Selamlar, 192.168.1.1 ve 192.168.1.255 ip adresleri arasında, yani 1'den 255e kadar bir döngü yardımıyla ICMP göndererek ip adresleri ayakta mı değil mi öğrenilebilir. Ancak router ayarlarında firewall açıksa ICMP bloklanabiliyor.

**Comment by Muzaffer188** [comment]
Selamlar, ICMP'nin bloklanmasına yönelik, döngü içerisinde firewall tarafından filtrelenen portlar için TCP ACK paketi göndererek filtrelenmiş portları tespit edip sonra bu portlara yönelik TCP FIN/NULL/XMAS paketleri ile de firewall atlamak denenebilir nmap'deki gibi veyahut normal TCP SYN paketi ile tarama yapıldığında açık olarak tespit edilen bir port varsa bu porta bağlanıp bu port içerisinde tekrar tarama yaparak da firewall un atlanması denebilir. Bu tarz yöntemler ile bir nebze de olsa firewall atlanabilir ancak yine firewall' bağlı olarak portların hepsi tespit edilemeyebilir. 
ilgili kaynaklar: 
https://nmap.org/book/firewall-subversion.html
https://nmap.org/book/determining-firewall-rules.html
https://nmap.org/book/scan-methods-null-fin-xmas-scan.html

**Comment by Sushkyn** [comment]
```
 #!/bin/bash

for i in {1..255}
do
    # ping
    ping -c 1 192.168.1.$i &>/dev/null

    # exit status
    if [ $? -eq 0 ]; then
        echo "192.168.1.$i is available."
    else
        echo "192.168.1.$i is not available."
    fi
done
```
Bu shell kodu ile firewall bypass edilerek lokal ip adresleri tespit edilebiliyor.
